### ISSUE TITLE
Right trigger haptic feedback not working

### ISSUE THREAD

**Issue by Choelniko** [ben-wes/pd-dualsense#18]
On macOS Sonoma 14.7.1 with an M2 chip, using Pd Vanilla 0.5-22, ther is an issue when sending haptic feedback values to the right trigger. Instead of activating the right trigger, the values are being addressed to the left trigger, while the right trigger itself does not respond at all. The left trigger functions as expected, behaving exactly as described in the help file.
I think the problem might be related to the offset (around line 280 in dslink.c) but I’m not experienced enough with C to fix it myself.
thanks a lot in advance for your help, and thanks again for making this external in the first place

**Comment by ben-wes** [comment]
thanks for your feedback! i wasn't aware that anyone besides me would actually be using this. ;)

i got several things wrong there:
* mixed up offsets for left and right trigger
* checked "left"/"right" symbols against the message symbol itself and not against the first argument (rather embarrassing!)

... it should be working now. i had to increase the offset of the trigger indices in the report by 1 in order to imitate the behavior of https://nondebug.github.io/dualsense/dualsense-explorer.html

not completely sure if that makes sense, but i can now set modes for both triggers. hope this works for you! there's a new release - maybe i should put this on deken at some point for simpler installation. but it's not completely working on windows and not tested on linux at all.

**Comment by ben-wes** [comment]
@Choelniko btw, i did not yet check out how these trigger definitions work exactly. could be nice to provide an abstraction to simplify the control with this repo. let me know if you have more experience with this and might want to contribute!
